- name: Copy kubeconfig to kubectl pod
  gather_facts: false
  hosts: kubectl
  tasks:
    - file:
        path: /.kube
        state: directory
    - sync:
        mode: push
        src: ~/.kube/config
        dest: /.kube/config
    - debug: var=zuul
    - command: kubectl apply -f nginx-k8s.yaml
      args:
        chdir: "{{ zuul.project.src_dir }}"
    - shell: sleep 5
    - command: kubectl describe deployment nginx-deployment
